apiVersion: v1
kind: Service
metadata:
  name: argo-x
  labels:
    name: argo-x-service
    app: harmony-stack
spec:
  type: NodePort
  ports:
    - port: 2746
      targetPort: 2746
      nodePort: 30100
  selector:
    app: argo-server
