apiVersion: v1
kind: Pod
metadata:
  name: harmony-app-pod
  labels:
    name: harmony-app-pod
    app: harmony-stack
spec:
  containers:
    - name: harmony-app
      image: harmony/harmony:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 3000
      env:
        - name: AWS_ACCESS_KEY_ID
          value: "harmony"
        - name: AWS_SECRET_ACCESS_KEY
          value: "harmony"
