apiVersion: v1
kind: Service
metadata:
  name: harmony-backend
  labels:
    name: harmony-backend-service
    app: harmony-stack
spec:
  ports:
    - port: 3001
      targetPort: 3001
  selector:
    name: harmony-app-pod
    app: harmony-stack
