apiVersion: v1
kind: Service
metadata:
  name: harmony-app
  labels:
    name: harmony-app-service
    app: harmony-stack
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
  selector:
    name: harmony-app-pod
    app: harmony-stack
