apiVersion: v1
kind: Pod
metadata:
  name: localstack-pod
  labels:
    name: localstack-pod
    app: harmony-stack
spec:
  containers:
    - name: localstack
      image: localstack/localstack:0.11.1
      ports:
        - containerPort: 4566
      env:
        - name: LOCALSTACK_SERVICES
          value: "s3,sts,sqs"
        - name: LOCALSTACK_DEBUG
          value: "1"
