apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    name: postgres-pod
    app: harmony-stack
spec:
  containers:
    - name: postgres
      image: postgres:12.4
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_USER
          value: "harmony"
        - name: POSTGRES_PASSWORD
          value: "harmony"
